### ISSUE TITLE
Tracking: Ingested dataset migration to OSN

### ISSUE THREAD

**Issue by jbusecke** [leap-stc/data-management#170]
- [ ] List all feedstocks below
- [ ] Set a timeline for when this will be finished
- [ ] Clean up the GCS storage

## Feedstocks to migrate
- https://github.com/leap-stc/eNATL_feedstock
- ...

## Feedstocks with migration in progress
-...

## Feedstocks migrated
- ...
